### ISSUE TITLE
cuboid-0.14.1 broken by Yampa update

### ISSUE THREAD

**Issue by peti** [pedromartins/cuboid#6]
Citing from http://hydra.cryp.to/build/795284/nixlog/1/raw:

    Input.hs:19:13: Not in scope: ‘count’

**Comment by pedromartins** [comment]
``count`` seems to have moved to Yampa.FRP.Integration. Fixed with c83a2758dd9b17f1d222634c0eecca4f4205bcae

**Comment by peti** [comment]
Will you release an updated version?

**Comment by pedromartins** [comment]
Trying to right now, but I uploaded the package before hackage had user accounts and now it is claiming I'm not the maintainer. I've emailed Hackage support to figure out how to fix that.

**Comment by pedromartins** [comment]
All fixed in 0.14.2: https://hackage.haskell.org/package/cuboid . Thanks for the report.

**Comment by peti** [comment]
Very cool, thank you!
